/**
 * Precomputes the cosmos force layout.  `npm run bake`
 *
 * The layout is a 500-tick n-body simulation over 118 nodes and 605 edges —
 * about 2.6 seconds. It used to run synchronously at module import, which meant
 * the browser sat on a blank screen before React could mount. Since the inputs
 * never change at runtime, the answer is baked here and shipped as data.
 *
 * The generated file carries a signature of the inputs; if the character or
 * relation set changes without a re-bake, the app notices and recomputes rather
 * than drawing a stale graph.
 */
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { characters, relations } from '../src/data/index';
import { computeLayout, layoutSignature } from '../src/lib/layout';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/layout.generated.ts');

const t0 = performance.now();
const { nodes } = computeLayout(characters, relations);
const ms = performance.now() - t0;

// Three decimals is well under a pixel at any camera distance and keeps the
// generated file about a third the size of full float output.
const r = (n: number) => Math.round(n * 1000) / 1000;
const rows = nodes.map((n) => `  ['${n.id}', ${r(n.x)}, ${r(n.y)}, ${r(n.z)}],`).join('\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/bake-layout.ts — do not edit.
// Re-run \`npm run bake\` after changing characters or relations.
//
// Baked positions for the cosmos graph: ${nodes.length} nodes, computed in
// ${ms.toFixed(0)}ms at build time so the browser never pays for it.

export const BAKED_SIGNATURE = '${layoutSignature(characters, relations)}';

/** [id, x, y, z] */
export const BAKED_NODES: [string, number, number, number][] = [
${rows}
];
`,
  'utf8'
);

console.log(`baked ${nodes.length} node positions in ${ms.toFixed(0)}ms -> src/data/layout.generated.ts`);
